openapi: 3.0.0
info:
  title: School Management API
  version: 1.0.0
  description: API of a school management with groups and student details.
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/HEIANDO14/student/1.0.0
  - url: "https:/hei-school.com"
paths:
  /students:
    get:
      summary: get all students
      parameters:
        - name: groupName
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: list of students
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'

    post:
      description: Add new student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '201':
          description: student add with success

    put:
      description: update a student information (idempotent).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '200':
          description: student information update with success

    delete:
      description: delete student with his ID.
      parameters:
        - name: id
          in: query
          description: student ID's to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: student deleted with success
  /students/{students}/group:
    put:
      responses:
        202:
          description: 'success'

  /groups:
    get:
      summary: get the list of all groups
      parameters:
        - name: groupName
          in: query
          description: Filter with the name of the group
          required: false
          schema:
            type: string
        - name: groupYear
          in: query
          required: false
          schema:
            type: string

      responses:
        '200':
          description: List of groups
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'

    post:
      description: create a new group.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
      responses:
        '201':
          description: group created with success

    put:
      summary: modify a group
      description: update group(idempotent).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
      responses:
        '200':
          description: update group with success

    delete:
      summary: delete a group
      description: delete group with his ID.
      parameters:
        - name: id
          in: query
          description: group's ID to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: group delete with success

components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: string
          description: unique student identify
      allOf:
        - $ref: '#/components/schemas/CreateStudent'
    CreateStudent:
      type: object
      properties:
        studentName:
          type: string
          description: student name's
        sex:
          type: string
          enum:
            - M
            - W
        birthdate:
          type: string
          format: date
        reference:
          type: string
          example: STD21001
      allOf:
        - $ref: '#/components/schemas/Group'
    Group:
      type: object
      allOf:
        - $ref: '#/components/schemas/CreateGroup'
      properties:
        groupId:
          type: string
          description: unique group identifier
    CreateGroup:
      type: object
      properties:
        groupName:
          type: string
          description: group name's
        groupYear:
          type: integer
        promotion:
          type: string
          description: the letter describe the year of the group (ex G means 2021-2022)
          enum:
            - G
            - H
            - J
            - K
        studentNb:
          type: number
          description: this is the number of all student on a group
        students:
          type: array
          items:
            $ref: "#/components/schemas/Student"
